SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, 
       REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO, (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXV
                 FROM REST_INFO
                 GROUP BY FOOD_TYPE) AS TAB
WHERE REST_INFO.FAVORITES = TAB.MAXV AND 
      REST_INFO.FOOD_TYPE = TAB.FOOD_TYPE
ORDER BY FOOD_TYPE DESC
