SELECT TB.MEMBER_NAME, REVIEW_TEXT, date_format(REVIEW_DATE, "%Y-%m-%d")
FROM (SELECT TA.MEMBER_ID, MEMBER_PROFILE.MEMBER_NAME
      FROM (SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            HAVING COUNT(REVIEW_ID)
                     = (SELECT COUNT(REVIEW_ID) AS CNT
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID
                        ORDER BY CNT DESC LIMIT 1)) AS TA 
            JOIN MEMBER_PROFILE ON MEMBER_PROFILE.MEMBER_ID = TA.MEMBER_ID) AS TB
     JOIN REST_REVIEW ON TB.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

// 최적화 할 방법을 생각해보자..
