SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, 
       COUNT(DISTINCT os.USER_ID) USERS
FROM ONLINE_SALE os JOIN USER_INFO ui ON ui.USER_ID = os.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

# DISTINCT 조건에 대해서 잘 생각 해볼 것!
