SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY 1 DESC

# ORDER BY TOTAL_DISTANCE를 하게 되면 문자열이라 정렬이 제대로 되지 않는다.
# 그래서 ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC로 정렬을 해야한다.
# 그런데 왜 ORDER BY 1로 해도 되는걸까?
