WITH LONGEST_FISH AS(
    SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, fi.LENGTH
FROM FISH_INFO fi INNER JOIN FISH_NAME_INFO fn ON fi.FISH_TYPE = fn.FISH_TYPE, LONGEST_FISH lf
WHERE fi.FISH_TYPE = lf.FISH_TYPE AND fi.LENGTH = lf.LENGTH
ORDER BY ID
