SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE LIKE "Intact %"
      AND (ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Spayed %" 
        OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Neutered %")
        
        
// 조금 더 어려운 JOIN 문제 풀어보기
