SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
       COUNT(DISTINCT ui.USER_ID) as PURCHASE_USER,
       ROUND((COUNT(DISTINCT ui.USER_ID) /
             (SELECT COUNT(*)
              FROM USER_INFO
              WHERE YEAR(JOINED) = 2021)), 1) as PURCHASED_RATIO
FROM USER_INFO ui INNER JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH

# SELECT 절에 Subquery를 적절히 잘 배치한 것 같다.
# 과연 성능은 어떨까?
