# CASE WHEN THEN문을 이용한 풀이

SELECT
CASE WHEN EXISTS(SELECT s.CODE FROM SKILLCODES s WHERE s.CODE & d.SKILL_CODE AND s.NAME = 'Python')
AND EXISTS(SELECT s.CODE FROM SKILLCODES s WHERE s.CODE & d.SKILL_CODE AND s.CATEGORY = 'Front End') THEN 'A'
WHEN EXISTS(SELECT s.CODE FROM SKILLCODES s WHERE s.CODE & d.SKILL_CODE AND s.NAME = 'C#') THEN 'B'
WHEN EXISTS(SELECT s.CODE FROM SKILLCODES s WHERE s.CODE & d.SKILL_CODE AND s.CATEGORY = 'Front End') THEN 'C'
ELSE NULL
END AS GRADE, d.ID, d.EMAIL
FROM DEVELOPERS d
HAVING GRADE IS NOT NULL
ORDER BY GRADE, d.ID
