WITH grade_table as(
    SELECT CASE WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    WHEN AVG(SCORE) < 80 THEN 'C' END AS GRADE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT he.EMP_NO, he.EMP_NAME, gt.GRADE,
CASE WHEN gt.GRADE = 'S' THEN he.SAL * 0.2
WHEN gt.GRADE = 'A' THEN he.SAL * 0.15
WHEN gt.GRADE = 'B' THEN he.SAL * 0.1
WHEN gt.GRADE = 'C' THEN 0 END AS BONUS
FROM HR_EMPLOYEES he INNER JOIN grade_table gt ON he.EMP_NO = gt.EMP_NO
ORDER BY he.EMP_NO
