WITH MAX_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS STD
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR, (STD - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ed, MAX_ECOLI me
WHERE YEAR(DIFFERENTIATION_DATE) = me.YEAR
ORDER BY YEAR, YEAR_DEV
