WITH RECURSIVE TEMP AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TEMP WHERE HOUR<23
)

SELECT HOUR, COUNT(ANIMAL_ID)
FROM TEMP LEFT OUTER JOIN ANIMAL_OUTS ON TEMP.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR
ORDER BY HOUR

# MySQL의 계층형 쿼리인 With Recursive를 이용해서 Table을 생성한다.
