SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%가죽시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%통풍시트%'
  // WHERE OPTIONS LIKE '%가죽시트' OR '%열선시트%' OR '%통풍시트%'
  // 위 문장은 제대로 안나옴
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE

SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE REGEXP_LIKE(OPTIONS, '가죽시트|열선시트|통풍시트')
  // 이렇게 정규식으로도 가능
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE
