SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%가죽시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%통풍시트%'
  // WHERE OPTIONS LIKE '%가죽시트' OR '%열선시트%' OR '%통풍시트%'
  // 두 구문의 차이는?
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE
