SELECT TA.APNT_NO, TA.PT_NAME, TA.PT_NO, TA.MCDP_CD, DOCTOR.DR_NAME, TA.APNT_YMD
FROM (SELECT PATIENT.PT_NO, PATIENT.PT_NAME, 
      MCDP_CD, MDDR_ID, APNT_CNCL_YN, APNT_YMD, APNT_NO
      FROM PATIENT JOIN APPOINTMENT ON PATIENT.PT_NO = APPOINTMENT.PT_NO
      WHERE APNT_CNCL_YN = 'N') AS TA
      JOIN DOCTOR ON TA.MDDR_ID = DOCTOR.DR_ID
WHERE MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13 AND TA.MCDP_CD = 'CS'
ORDER BY APNT_YMD

# 최적화 할 방법을 생각해보자.
