WITH FISH_INFO_WITHOUT_NULL AS (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(FISH_TYPE) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO_WITHOUT_NULL
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) > 33
ORDER BY FISH_TYPE
