SELECT FLAVOR
FROM (
    SELECT FLAVOR, sum(TOTAL) as TOTAL
    FROM(SELECT FH.FLAVOR, (FH.TOTAL_ORDER + JL.TOTAL_ORDER) as TOTAL
        FROM FIRST_HALF FH 
        LEFT JOIN JULY JL
        ON FH.FLAVOR = JL.FLAVOR) ORDERS
    GROUP BY FLAVOR) RESULT
ORDER BY TOTAL DESC
LIMIT 3 OFFSET 0