-- 코드를 입력하세요
SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO R1, 
    (SELECT REST_ID, FOOD_TYPE, max(FAVORITES) as FAVORITES 
    FROM REST_INFO 
    GROUP BY FOOD_TYPE 
    ORDER BY FOOD_TYPE DESC) R2
WHERE R1.FOOD_TYPE = R2.FOOD_TYPE and R1.FAVORITES = R2.FAVORITES
ORDER BY R1.FOOD_TYPE DESC