SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, 
RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as RI
LEFT JOIN REST_REVIEW as RR
ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%' and RR.REVIEW_SCORE IS NOT NULL
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC