SELECT P.ANIMAL_ID, P.NAME
FROM (
    SELECT I.ANIMAL_ID, (O.DATETIME - I.DATETIME) as DIFF, I.NAME
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME > I.DATETIME
    ORDER BY DIFF DESC
    LIMIT 2 OFFSET 0
) P
